### PR TITLE
Add dependancies as requirements.txt

### PR DESCRIPTION
**Pull request by amitness**
A **requirements.txt** file allows easy installation of all 3rd party libraries that the project depends on. I've generated that file for this script and also included instruction on how to use it in README.

### CODE REVIEW

**Comment by eastee** [comment]
The following packages are not necessary:
appdirs, packaging and pyparsing.
Mind to shed some light as to why do you see them as required?

**Comment by amitness** [comment]
The libraries that the project depends on are themselves built on top of some other 3rd party libraries.

For example, Flask is a popular web development framework which itself is built upon Jinja2 library. So when you install Flask, Jinja2 is autoinstalled.

In your case, the libraries such as pydub and SpeechSynthesis might be dependant on these, so they're auto included in requirements.txt.

**Comment by eastee** [comment]
I reviewed this requirements file again.
I do not think 'six' has a room here because it is not being used (I'm aware of its functionality).
Also, when installing dependencies using 'requirements.txt' file- any sub-dependencies (appdirs, packaging and pyparsing) are automatically installed.
I do not think they should be included.

**Comment by amitness** [comment]
@eastee I made the changes. I guess, it's good to merge now.

**Comment by eastee** [comment]
Thank you for your contribution 👍

**Pull request merged**
